---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: master
    service: ${REPO}	
    dir_name: null
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: npm
    script: |
      #!/bin/bash
      # The default Node.js version is 0.10.40
      # To use Node.js 0.10.48, uncomment the following line:
      #export PATH=/opt/IBM/node-v0.10.48/bin:$PATH
      # To use Node.js 0.12.7, uncomment the following line:
      #export PATH=/opt/IBM/node-v0.12/bin:$PATH
      # To use Node.js 4.4.5, uncomment the following line:
      #export PATH=/opt/IBM/node-v4.4.5/bin:$PATH
      # To use Node.js 6.7.0, uncomment the following line:
      #export PATH=/opt/IBM/node-v6.7.0/bin:$PATH
      node_version=v8.2.1
      install_name=node-v8.2.1-linux-x64
      if [ ! -e $install_name.tar.gz ]; then
      wget "http://nodejs.org/dist/$node_version/$install_name.tar.gz"
      echo 'Untarring'

      tar xf $install_name.tar.gz
      fi
      NODE_12_INSTALL_DIR=`pwd`/$install_name/bin
      PATH=$NODE_12_INSTALL_DIR:$PATH
      node -v
      export PATH=/opt/IBM/node-v8.2.1/bin:$PATH
      node --version
      npm --version
      rm $install_name.tar.gz
      npm install
- name: Deploy Stage
  inputs:
  - type: job
    stage: Build Stage
    job: Build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    deploy_permission: DEV_IN_SPACE
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      cf create-service cloudantNoSQLDB Lite dreamhome-finders-cloudant-01
      cf push "${CF_APP}"

      # View logs
      # cf logs "${CF_APP}" --recent
